NMUG/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NMUG.Models
{
	public class Meeting
	{

		[Key]
		public int Id { get; set; }

		[Display(Name = "Meeting Date")]
		[Required]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
		[DataType(DataType.Date, ErrorMessage = "Please enter a valid date (MM/DD/YYYY)")]
		//[DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)] 
		public DateTime MeetingDate { get; set; }

		[Display(Name = "Meeting Start Time")]
		[RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Please enter a valid Time (HH:MM AM|PM).")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
		//[DataType(DataType.Time, ErrorMessage = "Please enter a valid time (HH:MM AM|PM)")]
		public string MeetingStartTime { get; set; }

		[Display(Name = "Meeting End Time")]
		[RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Please enter a valid Time (HH:MM AM|PM).")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
		//[DataType(DataType.Time, ErrorMessage = "Please enter a valid time (HH:MM AM|PM)")]
		public string MeetingEndTime { get; set; }
        
        //TODO: dotnet ef migrations add -c 
        [Display(Name = "File Name")]
        public string FileName { get; set; }

		[Display(Name = "Location")]
		[RegularExpression(@"^[A-Z|\d]+[a-zA-Z''-'\d\s]*$", ErrorMessage = "First letter must be a capital letter or digit.")]
		public string MeetingLocation { get; set; }

		[Display(Name = "Presenter")]
		[RegularExpression(@"^[A-Z].*$", ErrorMessage = "First letter must be a capital letter.")]
		public string MeetingPresenter { get; set; }

		[Display(Name = "Description")]
		[DataType(DataType.MultilineText)]
		[StringLength(5000)]
		public string MeetingDescription { get; set; }

		[NotMapped]
		[Display(Name = "Time")]
		public string FromTo
		{
			get
			{
				return MeetingStartTime + " - " + MeetingEndTime;
			}
		}
		

		[NotMapped]
		// This is not mapped to DB
		public string DisplayFileName
		{
			get { return System.IO.Path.GetFileName(FileName); }
			private set { }
		}

	}
}

NMUG/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NMUG.Data;
using NMUG.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using NMUG.Helpers;
using NMUG.Services;
using Tweetinvi;
using Microsoft.Extensions.Options;

namespace NMUG.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IHostingEnvironment _environment;
        private TwitterAuthAPI _params;

        public MeetingsController(ApplicationDbContext context,  IHostingEnvironment environment, IOptions<TwitterAuthAPI> butter)
        {
            _context = context;
            _environment = environment;
            _params = butter.Value;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Meeting.ToListAsync());
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meeting.SingleOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // GET: Meetings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //Removed Id from Bind - MB 7/22
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MeetingDate,MeetingDescription,MeetingLocation,MeetingPresenter,MeetingStartTime,MeetingEndTime")] Meeting meeting, ICollection<IFormFile> files, TwitterAuthAPI _params)
        {

            if (ModelState.IsValid)
            {

                if (files != null)
                {
                    await Helpers.Upload.UploadFile(files, _environment);
                    meeting.FileName = Helpers.Upload.UploadFile(files);

                }

                _context.Add(meeting);

                TweetSender tweetMeeting = new TweetSender(_params);
                var tweet = meeting.MeetingDescription
                        + " at " + meeting.MeetingLocation
                        + " on " + meeting.MeetingDate.ToString("D")
                        + " at " + meeting.MeetingStartTime;

                tweetMeeting.PostTwitter(tweet);



                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(meeting);
        }

        // GET: Meetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meeting.SingleOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MeetingDate,MeetingDescription,MeetingLocation,MeetingPresenter,MeetingStartTime,MeetingEndTime")] Meeting meeting, ICollection<IFormFile> files)
        {

            if (id != meeting.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
               try
                {
                    if (files != null)

                        { 
                         await Helpers.Upload.UploadFile(files, _environment);
                         meeting.FileName = Helpers.Upload.UploadFile(files);
                        }

                    _context.Update(meeting);

                    TweetSender tweetMeeting = new TweetSender(_params);
                    var updateTweet = "UPDATE:" 
                        + meeting.MeetingDescription 
                        + " at " + meeting.MeetingLocation 
                        + " on " + meeting.MeetingDate.ToString("D")
                        + " at " + meeting.MeetingStartTime;

                    tweetMeeting.PostTwitter(updateTweet);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingExists(meeting.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(meeting);
        }

        // GET: Meetings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meeting.SingleOrDefaultAsync(m => m.Id == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meeting = await _context.Meeting.SingleOrDefaultAsync(m => m.Id == id);
            _context.Meeting.Remove(meeting);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool MeetingExists(int id)
        {
            return _context.Meeting.Any(e => e.Id == id);
        }
    }
}

NMUG/Controllers/MeetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace NMUG.Controllers
{
    public class MeetupController : Controller
    {

        //this is a property of the meetup controller, not a variable so no readonly
        private Models.MeetupAPIAuthToken _meetupauthtoken { get; }

        // injected meetupauthtoken into controller, now all methods in controller can access values in model
        public MeetupController(IOptions<Models.MeetupAPIAuthToken> meetupauthtoken)
        {
            _meetupauthtoken = meetupauthtoken.Value;
        }


        public async Task<IActionResult> Index()
        {
            var client = new HttpClient();

            var queryString = Uri.EscapeUriString(String.Format("events?key={0}&group_urlname={1}&sign=true", _meetupauthtoken.MeetupAPIKey, _meetupauthtoken.MeetupGroup));
            client.BaseAddress = new System.UriBuilder(_meetupauthtoken.MeetupBaseURL + queryString).Uri;
            client.DefaultRequestHeaders.Accept.Clear();


            var response = await client.GetAsync(client.BaseAddress);

            var responseString = await response.Content.ReadAsStringAsync();

            var searchResults = JsonConvert.DeserializeObject<Models.MeetupAPIResponse>(responseString);

            return View(searchResults);
        }



        // MODIFY this beyotch to create events on Meetup

        //public async Task<IActionResult> Create()
        //{

        // GET: MeetupAPIAuthToken/Create
        public IActionResult Create()
        {
            return View();
        }





    }
}

NMUG/Views/Meetings/Create.cshtml
@model NMUG.Models.Meeting

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create"  enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="MeetingDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger" />
            </div>
        </div>
		<div class="form-group">
			<label asp-for="MeetingStartTime" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="MeetingStartTime" class="form-control" />
				<span asp-validation-for="MeetingStartTime" class="text-danger" />
			</div>
		</div>
		<div class="form-group">
			<label asp-for="MeetingEndTime" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="MeetingEndTime" class="form-control" />
				<span asp-validation-for="MeetingEndTime" class="text-danger" />
			</div>
		</div>
        <div class="form-group">
            <label asp-for="MeetingDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingDescription" class="form-control" />
                <span asp-validation-for="MeetingDescription" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MeetingLocation" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingLocation" class="form-control" />
                <span asp-validation-for="MeetingLocation" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MeetingPresenter" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingPresenter" class="form-control" />
                <span asp-validation-for="MeetingPresenter" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FileName" class="col-md-2 control-label"></label>
             <div class="col-md-10">
                    <input type="file" name="files" multiple />
                    <br />
                </div>               
            </div>
         <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NMUG/Views/Meetings/Delete.cshtml
@model NMUG.Models.Meeting

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingPresenter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingPresenter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingLocation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingLocation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

NMUG/Views/Meetings/Details.cshtml
@model NMUG.Models.Meeting

@{
    ViewData["Title"] = "Meeting Details";
}

<h2>Meeting Details</h2>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FromTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FromTo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingPresenter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingPresenter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MeetingLocation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MeetingLocation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd>
            <a href="@Url.Content("~/uploads/" + Model.FileName)">@Html.DisplayFor(model => model.FileName)</a>
        </dd>
    </dl>
    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NMUG/Views/Meetings/Edit.cshtml
@model NMUG.Models.Meeting

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit"  enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Meeting</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="MeetingDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MeetingStartTime" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingStartTime" class="form-control" />
                <span asp-validation-for="MeetingStartTime" class="text-danger" />
            </div>
        </div>
		<div class="form-group">
			<label asp-for="MeetingEndTime" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="MeetingEndTime" class="form-control" />
				<span asp-validation-for="MeetingEndTime" class="text-danger" />
			</div>
		</div>
        <div class="form-group">
            <label asp-for="MeetingDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingDescription" class="form-control" />
                <span asp-validation-for="MeetingDescription" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MeetingPresenter" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingPresenter" class="form-control" />
                <span asp-validation-for="MeetingPresenter" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="MeetingLocation" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MeetingLocation" class="form-control" />
                <span asp-validation-for="MeetingLocation" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FileName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input type="file" name="files" multiple />
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NMUG/Views/Meetings/Index.cshtml
@model IEnumerable<NMUG.Models.Meeting>

@{
	ViewData["Title"] = "Index";
}

<h2>Meeting List</h2>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>

			<th>
				Date
			</th>
			<th>
				Time
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MeetingDescription)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MeetingPresenter)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MeetingLocation)
			</th>

			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.MeetingDate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.FromTo)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.MeetingDescription)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.MeetingPresenter)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.MeetingLocation)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>


<li><a asp-area="" asp-controller="Meetup" asp-action="Index">View listing of upcoming active Meetup Events</a></li>